# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  displayName: 'Checkout repository including submodules'
  submodules: true

- task: giuliovdev.hugo-extension.hugo-build-task-v2.HugoTask@2
  displayName: 'Generate Hugo site'
  inputs:
    source: 
    destination: '$(Build.ArtifactStagingDirectory)'
    extendedVersion: true
    hugoVersion: 0.92.2

- task: PublishPipelineArtifact@0
  displayName: 'Publish Hugo site as artifact'
  inputs:
    artifactName: 'hugo-site'
    targetPath: '$(Build.ArtifactStagingDirectory)'